version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo-data:/data/db

  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.9-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'